# Palo Alto Networks
## Career Promotin and Career Gap Analysis

In [57]:
%load_ext cudf.pandas
import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings('ignore')

The cudf.pandas extension is already loaded. To reload it, use:
  %reload_ext cudf.pandas

In [58]:
df = pd.read_csv("/kaggle/input/datasets/ashura369/hr-dataset/Palo Alto Networks.csv")

In [59]:
with pd.option_context("display.max_columns", None):
    display(df.head(10))

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,1,Travel_Rarely,1102,Sales,1,2,Life Sciences,2,Female,94,3,2,Sales Executive,4,Single,5993,19479,8,Yes,11,3,1,0,8,0,1,6,4,0,5
1,49,0,Travel_Frequently,279,Research & Development,8,1,Life Sciences,3,Male,61,2,2,Research Scientist,2,Married,5130,24907,1,No,23,4,4,1,10,3,3,10,7,1,7
2,37,1,Travel_Rarely,1373,Research & Development,2,2,Other,4,Male,92,2,1,Laboratory Technician,3,Single,2090,2396,6,Yes,15,3,2,0,7,3,3,0,0,0,0
3,33,0,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,4,Female,56,3,1,Research Scientist,3,Married,2909,23159,1,Yes,11,3,3,0,8,3,3,8,7,3,0
4,27,0,Travel_Rarely,591,Research & Development,2,1,Medical,1,Male,40,3,1,Laboratory Technician,2,Married,3468,16632,9,No,12,3,4,1,6,3,3,2,2,2,2
5,32,0,Travel_Frequently,1005,Research & Development,2,2,Life Sciences,4,Male,79,3,1,Laboratory Technician,4,Single,3068,11864,0,No,13,3,3,0,8,2,2,7,7,3,6
6,59,0,Travel_Rarely,1324,Research & Development,3,3,Medical,3,Female,81,4,1,Laboratory Technician,1,Married,2670,9964,4,Yes,20,4,1,3,12,3,2,1,0,0,0
7,30,0,Travel_Rarely,1358,Research & Development,24,1,Life Sciences,4,Male,67,3,1,Laboratory Technician,3,Divorced,2693,13335,1,No,22,4,2,1,1,2,3,1,0,0,0
8,38,0,Travel_Frequently,216,Research & Development,23,3,Life Sciences,4,Male,44,2,3,Manufacturing Director,3,Single,9526,8787,0,No,21,4,2,0,10,2,3,9,7,1,8
9,36,0,Travel_Rarely,1299,Research & Development,27,3,Medical,3,Male,94,3,2,Healthcare Representative,3,Married,5237,16577,6,No,13,3,2,2,17,3,2,7,7,7,7

In [60]:
df.isna().sum().sum()

np.int64(0)

In [61]:
print(df.columns)
print(len(df.columns))

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField',
       'EnvironmentSatisfaction', 'Gender', 'HourlyRate', 'JobInvolvement',
       'JobLevel', 'JobRole', 'JobSatisfaction', 'MaritalStatus',
       'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked', 'OverTime',
       'PercentSalaryHike', 'PerformanceRating', 'RelationshipSatisfaction',
       'StockOptionLevel', 'TotalWorkingYears', 'TrainingTimesLastYear',
       'WorkLifeBalance', 'YearsAtCompany', 'YearsInCurrentRole',
       'YearsSinceLastPromotion', 'YearsWithCurrManager'],
      dtype='object')
31

In [62]:
with pd.option_context("display.max_columns", None):
    display(df.select_dtypes(include='int'))

,Age,Attrition,DailyRate,DistanceFromHome,Education,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,JobSatisfaction,MonthlyIncome,MonthlyRate,NumCompaniesWorked,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,1,1102,1,2,2,94,3,2,4,5993,19479,8,11,3,1,0,8,0,1,6,4,0,5
1,49,0,279,8,1,3,61,2,2,2,5130,24907,1,23,4,4,1,10,3,3,10,7,1,7
2,37,1,1373,2,2,4,92,2,1,3,2090,2396,6,15,3,2,0,7,3,3,0,0,0,0
3,33,0,1392,3,4,4,56,3,1,3,2909,23159,1,11,3,3,0,8,3,3,8,7,3,0
4,27,0,591,2,1,1,40,3,1,2,3468,16632,9,12,3,4,1,6,3,3,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,0,884,23,2,3,41,4,2,4,2571,12290,4,17,3,3,1,17,3,3,5,2,0,3
1466,39,0,613,6,1,4,42,2,3,1,9991,21457,4,15,3,1,1,9,5,3,7,7,1,7
1467,27,0,155,4,3,2,87,4,2,2,6142,5174,1,20,4,2,1,6,0,3,6,2,0,3
1468,49,0,1023,2,3,4,63,2,2,2,5390,13243,2,14,3,4,0,17,3,2,9,6,0,8
1469,34,0,628,8,3,2,82,4,2,3,4404,10228,2,12,3,1,0,6,3,4,4,3,1,2

---

<h1 align='center'>Renaming Features</h1>

In [63]:
df.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField',
       'EnvironmentSatisfaction', 'Gender', 'HourlyRate', 'JobInvolvement',
       'JobLevel', 'JobRole', 'JobSatisfaction', 'MaritalStatus',
       'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked', 'OverTime',
       'PercentSalaryHike', 'PerformanceRating', 'RelationshipSatisfaction',
       'StockOptionLevel', 'TotalWorkingYears', 'TrainingTimesLastYear',
       'WorkLifeBalance', 'YearsAtCompany', 'YearsInCurrentRole',
       'YearsSinceLastPromotion', 'YearsWithCurrManager'],
      dtype='object')

In [64]:
change = {
    'BusinessTravel': 'Business Travel',
    'DailyRate': 'Compensation Rate',
    'DistanceFromHome': 'Distance From Home',
    'EducationField': 'Education Field',
    'EnvironmentSatisfaction': 'Environment Satisfaction',
    'HourlyRate': 'Hourly Rate',
    'JobInvolvement': 'Job Involvement',
    'JobLevel': 'Job Level',
    'JobRole': 'Job Role',
    'JobSatisfaction': 'Job Satisfaction',
    'MaritalStatus': 'Marital Status',
    'MonthlyIncome': 'Monthly Income',
    'MonthlyRate': 'Monthly Rate',
    'NumCompaniesWorked': 'Num Companies Worked',
    'OverTime': 'Over Time',
    'PercentSalaryHike': 'Percent Salary Hike',
    'PerformanceRating': 'Performance Rating',
    'RelationshipSatisfaction': 'Relationship Satisfaction',
    'StockOptionLevel': 'Stock Option Level',
    'TotalWorkingYears': 'Total Working Years',
    'TrainingTimesLastYear': 'Training Times Last Year',
    'WorkLifeBalance': 'Work Life Balance',
    'YearsAtCompany': 'Years At Company',
    'YearsInCurrentRole': 'Years In Current Role',
    'YearsSinceLastPromotion': 'Years Since Last Promotion',
    'YearsWithCurrManager': 'Years With Curr Manager'
}

df = df.rename(columns=change)

---

<h1 align='center'>Feature Labeling</h1>

`Education`

In [65]:
edu = {
    1:"Below College", 
    2:"College", 
    3:"Bachelor", 
    4:"Master", 
    5:"Doctor"
}

df['Education Labels'] = df['Education'].map(edu)

`Environment Satisfaction`

In [66]:
env_satisfaction = {
    1 : "Low", 
    2 : "Medium",
    3 : "High",
    4 : "Very High"
}

df['Environment Satisfaction Labels'] = df['Environment Satisfaction'].map(env_satisfaction)

`Job Involvement`

In [67]:
job_involv = {
    1: "Minimally Involved",
    2: "Moderately Involved",
    3: "Highly Involved",
    4: "Fully Dedicated"
}

df['Job Involvement Labels'] = df['Job Involvement'].map(job_involv)

`Job Level`

In [68]:
job_lvl = {
    1: 'Associate / Junior',
    2: 'Mid-Level',
    3: 'Senior',
    4: 'Staff / Principal',
    5: 'Director / VP'
}

df['Job Level Label'] = df['Job Level'].map(job_lvl)

`Relationship Satisfaction`

In [69]:
relation_satisfaction = {
    1: 'Very Dissatisfied',
    2: 'Dissatisfied',
    3: 'Satisfied',
    4: 'Very Satisfied'
}

df['Relationship Satisfaction Labels'] = df['Relationship Satisfaction'].map(relation_satisfaction)

`Total Working Years`

In [70]:
num_companies = df['Num Companies Worked'].replace(0, 0.5)
df['Avg Tenure Per Company'] = (df['Total Working Years'] / num_companies).round(1)

In [71]:
bins = [-1, 2.0, 5.0, float('inf')]
labels = [
    'Low Stability (< 2 yrs)',
    'Moderate Stability (2-5 yrs)',
    'High Stability (5+ yrs)'
]

df['Candidate Stability'] = pd.cut(df['Avg Tenure Per Company'],bins=bins,labels=labels,ordered=True)

`Training Times Last Year`

In [72]:
tenure = df['Years At Company'].replace(0, 0.5)

df['Training Intensity'] = (df['Training Times Last Year'] / tenure).round(2)

`Work Life Balance`

In [73]:
work_life = {
    1 : 'Poor',
    2 : 'Fair',
    3 : 'Good',
    4 : 'Excellent'
}

df['Work Life Balance Labels'] = df['Work Life Balance'].map(work_life)

`Years In Current Company`

In [80]:
df['Role Stagnation Index'] = (df['Years In Current Role'] / tenure).round(2)

`Years Since Last Promotion`

In [82]:
df['Promotion Gap Ratio'] = (df['Years Since Last Promotion'] / tenure).round(2)

`Years With Curr Manager`

In [87]:
bins = [-1,1,4,9, df['Years With Curr Manager'].max()]

labels1 = [1,2,3,4]

labels2 = [
    'New Relationship',
    'Developing',
    'Stable',
    'Highly Stable'
]

df['Manager Stability Indicator'] = pd.cut(df['Years With Curr Manager'], bins=bins, labels=labels1)
df['Manager Stability Indicator Labels'] = pd.cut(df['Years With Curr Manager'], bins=bins, labels=labels2)

---

### Saving the Dataset For Visualization

In [92]:
df.to_csv('Visualization Dataset', index=False)