# **EDA**

In [16]:
%load_ext cudf.pandas
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

The cudf.pandas extension is already loaded. To reload it, use:
  %reload_ext cudf.pandas

In [17]:
df = pd.read_csv("/kaggle/input/datasets/ashura369/late-delivery-prediction/APL_Logistics.csv", encoding="latin1")

In [18]:
df.head(5)

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Item Quantity,Sales,Order Item Total,Order Profit Per Order,Order Region,Order State,Order Status,Product Name,Product Price,Shipping Mode
0,DEBIT,6,4,159.69,472.45,Late delivery,1,9,Cardio Equipment,Brownsville,...,5,499.95,472.45,159.69,South Asia,Maharashtra,COMPLETE,Nike Men's Free 5.0+ Running Shoe,99.99,Standard Class
1,DEBIT,4,4,48.71,167.96,Shipping on time,0,29,Shop By Sport,Littleton,...,5,199.95,167.96,48.71,Central America,Cortés,ON_HOLD,Under Armour Girls' Toddler Spine Surge Runni,39.99,Standard Class
2,DEBIT,4,4,87.36,181.99,Shipping on time,0,48,Water Sports,Littleton,...,1,199.99,181.99,87.36,Central America,Cortés,ON_HOLD,Pelican Sunstream 100 Kayak,199.99,Standard Class
3,DEBIT,6,4,-41.89,175.99,Late delivery,1,48,Water Sports,Littleton,...,1,199.99,175.99,-41.89,East of USA,Nueva York,COMPLETE,Pelican Sunstream 100 Kayak,199.99,Standard Class
4,DEBIT,6,4,10.00,40.00,Late delivery,1,24,Women's Apparel,Littleton,...,1,50.00,40.00,10.00,East of USA,Nueva York,COMPLETE,Nike Men's Dri-FIT Victory Golf Polo,50.00,Standard Class

#### Checking for null values

In [19]:
df.isna().sum()

Type                             0
Days for shipping (real)         0
Days for shipment (scheduled)    0
Benefit per order                0
Sales per customer               0
Delivery Status                  0
Late_delivery_risk               0
Category Id                      0
Category Name                    0
Customer City                    0
Customer Country                 0
Customer Fname                   0
Customer Id                      0
Customer Lname                   8
Customer Segment                 0
Customer State                   0
Customer Street                  0
Customer Zipcode                 3
Department Id                    0
Department Name                  0
Latitude                         0
Longitude                        0
Market                           0
Order City                       0
Order Country                    0
Order Customer Id                0
Order Item Discount              0
Order Item Discount Rate         0
Order Item Product Price         0
Order Item Profit Ratio          0
Order Item Quantity              0
Sales                            0
Order Item Total                 0
Order Profit Per Order           0
Order Region                     0
Order State                      0
Order Status                     0
Product Name                     0
Product Price                    0
Shipping Mode                    0
dtype: int64

#### Checking for all column names

In [20]:
print(f"DATA SHAPE : {df.shape}\n")
print(f"TOTAL NUMBER OF COLUMNS : {len(df.columns)}")
print(f"\nCOLUMN NAMES : \n{df.columns}")

DATA SHAPE : (180519, 40)

TOTAL NUMBER OF COLUMNS : 40

COLUMN NAMES :
Index(['Type', 'Days for shipping (real)', 'Days for shipment (scheduled)',
       'Benefit per order', 'Sales per customer', 'Delivery Status',
       'Late_delivery_risk', 'Category Id', 'Category Name', 'Customer City',
       'Customer Country', 'Customer Fname', 'Customer Id', 'Customer Lname',
       'Customer Segment', 'Customer State', 'Customer Street',
       'Customer Zipcode', 'Department Id', 'Department Name', 'Latitude',
       'Longitude', 'Market', 'Order City', 'Order Country',
       'Order Customer Id', 'Order Item Discount', 'Order Item Discount Rate',
       'Order Item Product Price', 'Order Item Profit Ratio',
       'Order Item Quantity', 'Sales', 'Order Item Total',
       'Order Profit Per Order', 'Order Region', 'Order State', 'Order Status',
       'Product Name', 'Product Price', 'Shipping Mode'],
      dtype='object')

#### Checking for Datatypes contained in each cell

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 40 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Type                           180519 non-null  object
 1   Days for shipping (real)       180519 non-null  int64
 2   Days for shipment (scheduled)  180519 non-null  int64
 3   Benefit per order              180519 non-null  float64
 4   Sales per customer             180519 non-null  float64
 5   Delivery Status                180519 non-null  object
 6   Late_delivery_risk             180519 non-null  int64
 7   Category Id                    180519 non-null  int64
 8   Category Name                  180519 non-null  object
 9   Customer City                  180519 non-null  object
 10  Customer Country               180519 non-null  object
 11  Customer Fname                 180519 non-null  object
 12  Customer Id                    180519 non-null  int64
 13  Customer Lname                 180511 non-null  object
 14  Customer Segment               180519 non-null  object
 15  Customer State                 180519 non-null  object
 16  Customer Street                180519 non-null  object
 17  Customer Zipcode               180516 non-null  float64
 18  Department Id                  180519 non-null  int64
 19  Department Name                180519 non-null  object
 20  Latitude                       180519 non-null  float64
 21  Longitude                      180519 non-null  float64
 22  Market                         180519 non-null  object
 23  Order City                     180519 non-null  object
 24  Order Country                  180519 non-null  object
 25  Order Customer Id              180519 non-null  int64
 26  Order Item Discount            180519 non-null  float64
 27  Order Item Discount Rate       180519 non-null  float64
 28  Order Item Product Price       180519 non-null  float64
 29  Order Item Profit Ratio        180519 non-null  float64
 30  Order Item Quantity            180519 non-null  int64
 31  Sales                          180519 non-null  float64
 32  Order Item Total               180519 non-null  float64
 33  Order Profit Per Order         180519 non-null  float64
 34  Order Region                   180519 non-null  object
 35  Order State                    180519 non-null  object
 36  Order Status                   180519 non-null  object
 37  Product Name                   180519 non-null  object
 38  Product Price                  180519 non-null  float64
 39  Shipping Mode                  180519 non-null  object
dtypes: float64(13), int64(8), object(19)
memory usage: 55.1+ MB

In [22]:
df.columns.unique()

Index(['Type', 'Days for shipping (real)', 'Days for shipment (scheduled)',
       'Benefit per order', 'Sales per customer', 'Delivery Status',
       'Late_delivery_risk', 'Category Id', 'Category Name', 'Customer City',
       'Customer Country', 'Customer Fname', 'Customer Id', 'Customer Lname',
       'Customer Segment', 'Customer State', 'Customer Street',
       'Customer Zipcode', 'Department Id', 'Department Name', 'Latitude',
       'Longitude', 'Market', 'Order City', 'Order Country',
       'Order Customer Id', 'Order Item Discount', 'Order Item Discount Rate',
       'Order Item Product Price', 'Order Item Profit Ratio',
       'Order Item Quantity', 'Sales', 'Order Item Total',
       'Order Profit Per Order', 'Order Region', 'Order State', 'Order Status',
       'Product Name', 'Product Price', 'Shipping Mode'],
      dtype='object')

#### Printing Column Names, dtypes, Unique values, and the data they contain

In [23]:
elements = [
    df[col].unique().tolist() for col in df.columns
]

pd.DataFrame({
    'DTYPES' : df.dtypes,
    'UNIQUE VALUES' : df.nunique(),
    'ELEMENTS' : elements                   # Here we have put all the elements who have unique values less than 20
})

,DTYPES,UNIQUE VALUES,ELEMENTS
Type,object,4,"[DEBIT, PAYMENT, TRANSFER, CASH]"
Days for shipping (real),int64,7,"[6, 4, 3, 0, 5, 2, 1]"
Days for shipment (scheduled),int64,4,"[4, 0, 1, 2]"
Benefit per order,float64,21998,"[159.69, 48.71, 87.36, -41.89, 10.0, 105.63, 6..."
Sales per customer,float64,2927,"[472.45, 167.96, 181.99, 175.99, 40.0, 290.98,..."
Delivery Status,object,4,"[Late delivery, Shipping on time, Advance ship..."
Late_delivery_risk,int64,2,"[1, 0]"
Category Id,int64,51,"[9, 29, 48, 24, 43, 46, 45, 17, 13, 18, 40, 11..."
Category Name,object,50,"[Cardio Equipment, Shop By Sport, Water Sports..."
Customer City,object,563,"[Brownsville, Littleton, Caguas, San Marcos, P..."
Customer Country,object,2,"[EE. UU., Puerto Rico]"
Customer Fname,object,782,"[Richard, Mary, Ann, Robert, Melissa, Megan, C..."
Customer Id,int64,20652,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14..."
Customer Lname,object,1109,"[Hernandez, Barrett, Smith, Jones, Hudson, Wil..."
Customer Segment,object,3,"[Consumer, Home Office, Corporate]"
Customer State,object,46,"[TX, CO, PR, CA, NJ, MA, VA, MI, AZ, IL, WA, N..."
Customer Street,object,7458,"[6303 Heather Plaza, 9526 Noble Embers Ridge, ..."
Customer Zipcode,float64,995,"[78521.0, 80126.0, 725.0, 92069.0, 7055.0, 184..."
Department Id,int64,11,"[3, 5, 7, 4, 6, 2, 8, 9, 10, 12, 11]"
Department Name,object,11,"[Footwear, Golf, Fan Shop, Apparel, Outdoors, ..."
Latitude,float64,11250,"[25.95364761, 38.37559509, 18.02537537, 33.670..."
Longitude,float64,4487,"[-97.5076828, -104.7260208, -66.61508179, -112..."
Market,object,5,"[Pacific Asia, LATAM, USCA, Europe, Africa]"
Order City,object,3597,"[Mumbai, San Pedro Sula, New York City, Rome, ..."
Order Country,object,164,"[India, Honduras, Estados Unidos, Italia, Alem..."
Order Customer Id,int64,20652,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14..."
Order Item Discount,float64,1017,"[27.5, 31.99, 18.0, 24.0, 10.0, 9.0, 7.5, 15.9..."
Order Item Discount Rate,float64,18,"[0.06, 0.16, 0.09, 0.12, 0.2, 0.03, 0.05, 0.18..."
Order Item Product Price,float64,75,"[99.99, 39.99, 199.99, 50.0, 299.98, 49.98, 39..."
Order Item Profit Ratio,float64,162,"[0.34, 0.29, 0.48, -0.24, 0.25, 0.36, 0.45, 0...."
Order Item Quantity,int64,5,"[5, 1, 3, 2, 4]"
Sales,float64,193,"[499.95, 199.95, 199.99, 50.0, 299.98, 149.94,..."
Order Item Total,float64,2927,"[472.45, 167.96, 181.99, 175.99, 40.0, 290.98,..."
Order Profit Per Order,float64,21998,"[159.69, 48.71, 87.36, -41.89, 10.0, 105.63, 6..."
Order Region,object,23,"[South Asia, Central America, East of USA, Sou..."
Order State,object,1089,"[Maharashtra, Cortés, Nueva York, Lacio, Bavar..."
Order Status,object,9,"[COMPLETE, ON_HOLD, PENDING_PAYMENT, PENDING, ..."
Product Name,object,118,"[Nike Men's Free 5.0+ Running Shoe, Under Armo..."
Product Price,float64,75,"[99.99, 39.99, 199.99, 50.0, 299.98, 49.98, 39..."
Shipping Mode,object,4,"[Standard Class, Same Day, First Class, Second..."

### Observation

In this step, we drop columns that are not useful for our descriptive analysis and visualization. Removing these columns helps reduce memory usage, declutters the DataFrame, and makes it easier to display tables and plots.

**The columns are to be removed based on the following categories:**

1. **Personally Identifiable Information (PII) & Privacy:**
   * `Customer Fname` & `Customer Lname`: Customer names are unique to individuals and do not provide any aggregatable business insights.
   * `Customer Street`: Street-level addresses are too granular for high-level geographic charts.

2. **Database Keys & Unique Identifiers (IDs):**
   * `Customer Id`, `Order Customer Id`, `Category Id`, and `Department Id`: These are database keys used for table joins. For visualization, the descriptive names (like `Category Name` or `Department Name`) are used instead of numeric IDs.

3. **Redundant Columns:**
   * `Order Item Product Price`: This is redundant since we already have `Product Price`.
   * `Customer Zipcode`: Zip codes have too many unique values to visualize effectively on charts (we use broader regions like `Customer State` or `Customer City` instead).

4. **Excluded Metrics (Optional):**
   * `Order Profit Per Order`: Excluded from this specific visualization subset because we already have a similar column to this.

---

### **Preparaing a dataset for EDA** 
- To be visualized in Power BI

In [24]:
data = df.drop(columns=['Category Id','Customer Fname','Customer Lname','Customer Id','Customer Street','Customer Zipcode','Department Id','Order Customer Id','Order Item Product Price','Order Profit Per Order'])

#### Replacing 1 to YES and 0 to NO

In [28]:
data['Late_delivery_risk'] = data['Late_delivery_risk'].map({1:'YES', 0:'NO'})

In [29]:
with pd.option_context('display.max_columns',None):                      # will print the dataset with all the columns (no columns will be kept hidden)
    display(data.head(6))

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Name,Customer City,Customer Country,Customer Segment,Customer State,Department Name,Latitude,Longitude,Market,Order City,Order Country,Order Item Discount,Order Item Discount Rate,Order Item Profit Ratio,Order Item Quantity,Sales,Order Item Total,Order Region,Order State,Order Status,Product Name,Product Price,Shipping Mode
0,DEBIT,6,4,159.69,472.45,Late delivery,YES,Cardio Equipment,Brownsville,EE. UU.,Consumer,TX,Footwear,25.953648,-97.507683,Pacific Asia,Mumbai,India,27.50,0.06,0.34,5,499.95,472.45,South Asia,Maharashtra,COMPLETE,Nike Men's Free 5.0+ Running Shoe,99.99,Standard Class
1,DEBIT,4,4,48.71,167.96,Shipping on time,NO,Shop By Sport,Littleton,EE. UU.,Consumer,CO,Golf,38.375595,-104.726021,LATAM,San Pedro Sula,Honduras,31.99,0.16,0.29,5,199.95,167.96,Central America,Cortés,ON_HOLD,Under Armour Girls' Toddler Spine Surge Runni,39.99,Standard Class
2,DEBIT,4,4,87.36,181.99,Shipping on time,NO,Water Sports,Littleton,EE. UU.,Consumer,CO,Fan Shop,38.375595,-104.726021,LATAM,San Pedro Sula,Honduras,18.00,0.09,0.48,1,199.99,181.99,Central America,Cortés,ON_HOLD,Pelican Sunstream 100 Kayak,199.99,Standard Class
3,DEBIT,6,4,-41.89,175.99,Late delivery,YES,Water Sports,Littleton,EE. UU.,Consumer,CO,Fan Shop,38.375595,-104.726021,USCA,New York City,Estados Unidos,24.00,0.12,-0.24,1,199.99,175.99,East of USA,Nueva York,COMPLETE,Pelican Sunstream 100 Kayak,199.99,Standard Class
4,DEBIT,6,4,10.00,40.00,Late delivery,YES,Women's Apparel,Littleton,EE. UU.,Consumer,CO,Golf,38.375595,-104.726021,USCA,New York City,Estados Unidos,10.00,0.20,0.25,1,50.00,40.00,East of USA,Nueva York,COMPLETE,Nike Men's Dri-FIT Victory Golf Polo,50.00,Standard Class
5,DEBIT,6,4,105.63,290.98,Late delivery,YES,Camping & Hiking,Littleton,EE. UU.,Consumer,CO,Fan Shop,38.375595,-104.726021,USCA,New York City,Estados Unidos,9.00,0.03,0.36,1,299.98,290.98,East of USA,Nueva York,COMPLETE,Diamondback Women's Serene Classic Comfort Bi,299.98,Standard Class

In [30]:
print(f"TOTAL NUMBER OF COLUMNS : {data.shape[1]}")
print(f"COLUMNS REMOVED : {df.shape[1] - data.shape[1]}")

TOTAL NUMBER OF COLUMNS : 30
COLUMNS REMOVED : 10

In [31]:
data.describe()

,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Latitude,Longitude,Order Item Discount,Order Item Discount Rate,Order Item Profit Ratio,Order Item Quantity,Sales,Order Item Total,Product Price
count,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000
mean,3.497654,2.931847,21.974989,183.107607,29.719955,-84.915675,20.664741,0.101668,0.120647,2.127638,203.772092,183.107607,141.232547
std,1.623722,1.374449,104.433526,120.043668,9.813646,21.433241,21.800901,0.070415,0.466796,1.453451,132.273075,120.043668,139.732489
min,0.000000,0.000000,-4274.980000,7.490000,-33.937553,-158.025986,0.000000,0.000000,-2.750000,1.000000,9.990000,7.490000,9.990000
25%,2.000000,2.000000,7.000000,104.380000,18.265432,-98.446312,5.400000,0.040000,0.080000,1.000000,119.980000,104.380000,50.000000
50%,3.000000,4.000000,31.520000,163.990000,33.144863,-76.847908,14.000000,0.100000,0.270000,1.000000,199.920000,163.990000,59.990000
75%,5.000000,4.000000,64.800000,247.400000,39.279617,-66.370583,29.990000,0.160000,0.360000,3.000000,299.950000,247.400000,199.990000
max,6.000000,4.000000,911.800000,1939.990000,48.781933,115.263077,500.000000,0.250000,0.500000,5.000000,1999.990000,1939.990000,1999.990000

### Saving the dataset to excel to visualize in Power BI

In [34]:
data.to_excel("visualization_data.xlsx",index=False)