In [67]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

In [68]:
df = pd.read_csv("dataset/APL_Logistics.csv", encoding="latin1")

In [69]:
df.head(5)

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Item Quantity,Sales,Order Item Total,Order Profit Per Order,Order Region,Order State,Order Status,Product Name,Product Price,Shipping Mode
0,DEBIT,6,4,159.69,472.45,Late delivery,1,9,Cardio Equipment,Brownsville,...,5,499.95,472.45,159.69,South Asia,Maharashtra,COMPLETE,Nike Men's Free 5.0+ Running Shoe,99.99,Standard Class
1,DEBIT,4,4,48.71,167.96,Shipping on time,0,29,Shop By Sport,Littleton,...,5,199.95,167.96,48.71,Central America,Cortés,ON_HOLD,Under Armour Girls' Toddler Spine Surge Runni,39.99,Standard Class
2,DEBIT,4,4,87.36,181.99,Shipping on time,0,48,Water Sports,Littleton,...,1,199.99,181.99,87.36,Central America,Cortés,ON_HOLD,Pelican Sunstream 100 Kayak,199.99,Standard Class
3,DEBIT,6,4,-41.89,175.99,Late delivery,1,48,Water Sports,Littleton,...,1,199.99,175.99,-41.89,East of USA,Nueva York,COMPLETE,Pelican Sunstream 100 Kayak,199.99,Standard Class
4,DEBIT,6,4,10.00,40.00,Late delivery,1,24,Women's Apparel,Littleton,...,1,50.00,40.00,10.00,East of USA,Nueva York,COMPLETE,Nike Men's Dri-FIT Victory Golf Polo,50.00,Standard Class

#### Checking for null values

In [70]:
df.isna().sum()

Type                             0
Days for shipping (real)         0
Days for shipment (scheduled)    0
Benefit per order                0
Sales per customer               0
Delivery Status                  0
Late_delivery_risk               0
Category Id                      0
Category Name                    0
Customer City                    0
Customer Country                 0
Customer Fname                   0
Customer Id                      0
Customer Lname                   8
Customer Segment                 0
Customer State                   0
Customer Street                  0
Customer Zipcode                 3
Department Id                    0
Department Name                  0
Latitude                         0
Longitude                        0
Market                           0
Order City                       0
Order Country                    0
Order Customer Id                0
Order Item Discount              0
Order Item Discount Rate         0
Order Item Product Price         0
Order Item Profit Ratio          0
Order Item Quantity              0
Sales                            0
Order Item Total                 0
Order Profit Per Order           0
Order Region                     0
Order State                      0
Order Status                     0
Product Name                     0
Product Price                    0
Shipping Mode                    0
dtype: int64

#### Checking for all column names

In [71]:
print(f"DATA SHAPE : {df.shape}\n")
print(f"TOTAL NUMBER OF COLUMNS : {len(df.columns)}")
print(f"\nCOLUMN NAMES : \n{df.columns}")

DATA SHAPE : (180519, 40)

TOTAL NUMBER OF COLUMNS : 40

COLUMN NAMES :
Index(['Type', 'Days for shipping (real)', 'Days for shipment (scheduled)',
       'Benefit per order', 'Sales per customer', 'Delivery Status',
       'Late_delivery_risk', 'Category Id', 'Category Name', 'Customer City',
       'Customer Country', 'Customer Fname', 'Customer Id', 'Customer Lname',
       'Customer Segment', 'Customer State', 'Customer Street',
       'Customer Zipcode', 'Department Id', 'Department Name', 'Latitude',
       'Longitude', 'Market', 'Order City', 'Order Country',
       'Order Customer Id', 'Order Item Discount', 'Order Item Discount Rate',
       'Order Item Product Price', 'Order Item Profit Ratio',
       'Order Item Quantity', 'Sales', 'Order Item Total',
       'Order Profit Per Order', 'Order Region', 'Order State', 'Order Status',
       'Product Name', 'Product Price', 'Shipping Mode'],
      dtype='str')

#### Checking for Datatypes contained in each cell

In [72]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 40 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Type                           180519 non-null  str
 1   Days for shipping (real)       180519 non-null  int64
 2   Days for shipment (scheduled)  180519 non-null  int64
 3   Benefit per order              180519 non-null  float64
 4   Sales per customer             180519 non-null  float64
 5   Delivery Status                180519 non-null  str
 6   Late_delivery_risk             180519 non-null  int64
 7   Category Id                    180519 non-null  int64
 8   Category Name                  180519 non-null  str
 9   Customer City                  180519 non-null  str
 10  Customer Country               180519 non-null  str
 11  Customer Fname                 180519 non-null  str
 12  Customer Id                    180519 non-null  int64
 13  Customer Lname                 180511 non-null  str
 14  Customer Segment               180519 non-null  str
 15  Customer State                 180519 non-null  str
 16  Customer Street                180519 non-null  str
 17  Customer Zipcode               180516 non-null  float64
 18  Department Id                  180519 non-null  int64
 19  Department Name                180519 non-null  str
 20  Latitude                       180519 non-null  float64
 21  Longitude                      180519 non-null  float64
 22  Market                         180519 non-null  str
 23  Order City                     180519 non-null  str
 24  Order Country                  180519 non-null  str
 25  Order Customer Id              180519 non-null  int64
 26  Order Item Discount            180519 non-null  float64
 27  Order Item Discount Rate       180519 non-null  float64
 28  Order Item Product Price       180519 non-null  float64
 29  Order Item Profit Ratio        180519 non-null  float64
 30  Order Item Quantity            180519 non-null  int64
 31  Sales                          180519 non-null  float64
 32  Order Item Total               180519 non-null  float64
 33  Order Profit Per Order         180519 non-null  float64
 34  Order Region                   180519 non-null  str
 35  Order State                    180519 non-null  str
 36  Order Status                   180519 non-null  str
 37  Product Name                   180519 non-null  str
 38  Product Price                  180519 non-null  float64
 39  Shipping Mode                  180519 non-null  str
dtypes: float64(13), int64(8), str(19)
memory usage: 55.1 MB

In [73]:
df.columns.unique()

Index(['Type', 'Days for shipping (real)', 'Days for shipment (scheduled)',
       'Benefit per order', 'Sales per customer', 'Delivery Status',
       'Late_delivery_risk', 'Category Id', 'Category Name', 'Customer City',
       'Customer Country', 'Customer Fname', 'Customer Id', 'Customer Lname',
       'Customer Segment', 'Customer State', 'Customer Street',
       'Customer Zipcode', 'Department Id', 'Department Name', 'Latitude',
       'Longitude', 'Market', 'Order City', 'Order Country',
       'Order Customer Id', 'Order Item Discount', 'Order Item Discount Rate',
       'Order Item Product Price', 'Order Item Profit Ratio',
       'Order Item Quantity', 'Sales', 'Order Item Total',
       'Order Profit Per Order', 'Order Region', 'Order State', 'Order Status',
       'Product Name', 'Product Price', 'Shipping Mode'],
      dtype='str')

In [74]:
elements = [
    df[col].unique().tolist() for col in df.columns
]

pd.DataFrame({
    'DTYPES' : df.dtypes,
    'UNIQUE VALUES' : df.nunique(),
    'ELEMENTS' : elements                   # Here we have put all the elements who have unique values less than 20
})

,DTYPES,UNIQUE VALUES,ELEMENTS
Type,str,4,"[DEBIT, PAYMENT, TRANSFER, CASH]"
Days for shipping (real),int64,7,"[6, 4, 3, 0, 5, 2, 1]"
Days for shipment (scheduled),int64,4,"[4, 0, 1, 2]"
Benefit per order,float64,21998,"[159.69, 48.71, 87.36, -41.89, 10.0, 105.63, 6..."
Sales per customer,float64,2927,"[472.45, 167.96, 181.99, 175.99, 40.0, 290.98,..."
Delivery Status,str,4,"[Late delivery, Shipping on time, Advance ship..."
Late_delivery_risk,int64,2,"[1, 0]"
Category Id,int64,51,"[9, 29, 48, 24, 43, 46, 45, 17, 13, 18, 40, 11..."
Category Name,str,50,"[Cardio Equipment, Shop By Sport, Water Sports..."
Customer City,str,563,"[Brownsville, Littleton, Caguas, San Marcos, P..."
Customer Country,str,2,"[EE. UU., Puerto Rico]"
Customer Fname,str,782,"[Richard, Mary, Ann, Robert, Melissa, Megan, C..."
Customer Id,int64,20652,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14..."
Customer Lname,str,1109,"[Hernandez, Barrett, Smith, Jones, Hudson, Wil..."
Customer Segment,str,3,"[Consumer, Home Office, Corporate]"
Customer State,str,46,"[TX, CO, PR, CA, NJ, MA, VA, MI, AZ, IL, WA, N..."
Customer Street,str,7458,"[6303 Heather Plaza, 9526 Noble Embers Ridge, ..."
Customer Zipcode,float64,995,"[78521.0, 80126.0, 725.0, 92069.0, 7055.0, 184..."
Department Id,int64,11,"[3, 5, 7, 4, 6, 2, 8, 9, 10, 12, 11]"
Department Name,str,11,"[Footwear, Golf, Fan Shop, Apparel, Outdoors, ..."
Latitude,float64,11250,"[25.95364761, 38.37559509, 18.02537537, 33.670..."
Longitude,float64,4487,"[-97.5076828, -104.7260208, -66.61508179, -112..."
Market,str,5,"[Pacific Asia, LATAM, USCA, Europe, Africa]"
Order City,str,3597,"[Mumbai, San Pedro Sula, New York City, Rome, ..."
Order Country,str,164,"[India, Honduras, Estados Unidos, Italia, Alem..."
Order Customer Id,int64,20652,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14..."
Order Item Discount,float64,1017,"[27.5, 31.99, 18.0, 24.0, 10.0, 9.0, 7.5, 15.9..."
Order Item Discount Rate,float64,18,"[0.06, 0.16, 0.09, 0.12, 0.2, 0.03, 0.05, 0.18..."
Order Item Product Price,float64,75,"[99.99, 39.99, 199.99, 50.0, 299.98, 49.98, 39..."
Order Item Profit Ratio,float64,162,"[0.34, 0.29, 0.48, -0.24, 0.25, 0.36, 0.45, 0...."
Order Item Quantity,int64,5,"[5, 1, 3, 2, 4]"
Sales,float64,193,"[499.95, 199.95, 199.99, 50.0, 299.98, 149.94,..."
Order Item Total,float64,2927,"[472.45, 167.96, 181.99, 175.99, 40.0, 290.98,..."
Order Profit Per Order,float64,21998,"[159.69, 48.71, 87.36, -41.89, 10.0, 105.63, 6..."
Order Region,str,23,"[South Asia, Central America, East of USA, Sou..."
Order State,str,1089,"[Maharashtra, Cortés, Nueva York, Lacio, Bavar..."
Order Status,str,9,"[COMPLETE, ON_HOLD, PENDING_PAYMENT, PENDING, ..."
Product Name,str,118,"[Nike Men's Free 5.0+ Running Shoe, Under Armo..."
Product Price,float64,75,"[99.99, 39.99, 199.99, 50.0, 299.98, 49.98, 39..."
Shipping Mode,str,4,"[Standard Class, Same Day, First Class, Second..."

#### Printing the Duplicated Columns

In [75]:
duplicate_cols = df.T.duplicated()
print(df.columns[duplicate_cols])

Index(['Order Customer Id', 'Order Item Total', 'Order Profit Per Order',
       'Product Price'],
      dtype='str')