In [22]:
%load_ext cudf.pandas
import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings('ignore')

The cudf.pandas extension is already loaded. To reload it, use:
  %reload_ext cudf.pandas

In [23]:
df = pd.read_excel("/kaggle/input/datasets/ashura369/visualization-dataset/Visualisation Dataset.xlsx")

In [24]:
print(f"SHAPE OF THE DATASET : {df.shape}")

with pd.option_context('display.max_columns', None):
    display(df.sample(8))

SHAPE OF THE DATASET : (10000, 23)

,unit_category,tower_number,floor_area_sqft,size_segment,transaction_date,transaction_quarters,transaction_month,transaction_day,sale_price,price_segment,listing_status,client_id,client_type,date_of_birth,age,age_segment,gender,country,region,acquisition_purpose,satisfaction_score,loan_applied,referral_channel
6047,Apartment,2,924.40,Standard,2025-01-01,1,January,Wednesday,282193.58,Budget,Sold,C1989,Individual,1959-11-19,66.0,Retirees,M,USA,Texas,Home,3.0,No,Agency
5960,Apartment,19,1599.44,Spacious,2024-12-01,4,December,Sunday,521125.08,Premium,Sold,C0321,Individual,1992-01-12,34.0,Peak Earners,M,USA,California,Investment,2.0,No,Agency
3734,Apartment,6,1408.23,Spacious,2024-08-01,3,August,Thursday,438900.35,Mid-market,Sold,C0456,Individual,1995-11-18,30.0,Young Professionals,F,USA,Oregon,Home,3.0,Yes,Website
5341,Apartment,14,803.50,Standard,2024-11-01,4,November,Friday,228990.94,Budget,Sold,C0080,Individual,1949-01-16,77.0,Retirees,F,USA,California,Investment,3.0,No,Website
6320,Apartment,19,1137.59,Standard,2025-01-01,1,January,Wednesday,321045.92,Mid-market,Sold,C1020,Individual,1994-07-23,32.0,Peak Earners,F,USA,California,Home,3.0,No,Agency
9030,Office,1,1439.52,Spacious,2025-10-01,4,October,Wednesday,411692.78,Mid-market,Sold,C0335,Individual,1975-12-24,50.0,Peak Earners,M,USA,Arizona,Home,4.0,No,Website
6046,Apartment,2,924.40,Standard,2025-01-01,1,January,Wednesday,268881.64,Budget,Sold,C1843,Individual,1952-06-18,74.0,Retirees,M,Germany,Hesse,Home,4.0,No,Website
7014,Apartment,1,740.83,Compact,2025-04-01,2,April,Tuesday,221183.29,Budget,Available,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
pd.set_option('display.max_colwidth', None)          # Expands The DataFrame To Its Max Width

pd.DataFrame({
    'DATA TYPE' : df.dtypes,
    'NO. OF UNIQUE VALUES' : df.nunique(),
    'UNIQUE VALUES' : [df[i].unique() for i in df.columns]
})

,DATA TYPE,NO. OF UNIQUE VALUES,UNIQUE VALUES
unit_category,object,2,"[Apartment, Office]"
tower_number,int64,20,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]"
floor_area_sqft,float64,1208,"[1160.36, 782.25, 756.21, 743.09, 701.66, 927.8299999999999, 1109.25, 1132.06, 670.89, 1596.35, 781.07, 785.48, 798.5, 798.2800000000001, 748.06, 715.6700000000001, 788.73, 633.61, 740.75, 719.47, 1181.69, 1146.24, 1957.16, 740.8299999999999, 1201.5, 1146.11, 1154.92, 757.2, 753.2900000000001, 619.7800000000001, 1168.59, 613.59, 788.72, 1281.85, 715.54, 584.19, 788.7900000000001, 1625.05, 1397.4, 727.55, 943.48, 1577.79, 650.6700000000001, 1107.33, 931.4, 1118.94, 697.74, 708.3199999999999, 1617.9, 1604.8, 722.22, 689.75, 668.89, 744.01, 1125.84, 784.09, 802.97, 1122.15, 776.04, 765.56, 1117.14, 679.93, 733.4499999999999, 1343.96, 691.09, 1174.48, 693.8499999999999, 1179.42, 1607.94, 1588.14, 1353.02, 1615.98, 1630.82, 786.98, 789.38, 809.06, 760.39, 780.6800000000001, 1294.91, 801.66, 1110.99, 1307.35, 734.73, 779.87, 1160.48, 800.23, 805.88, 802.11, 799.1, 775.8499999999999, 793.56, 629.2700000000001, 624.9599999999999, 804.8399999999999, 1006.65, 1278.6, 786.2800000000001, 1051.39, 1787.13, 627.56, ...]"
size_segment,object,3,"[Standard, Compact, Spacious]"
transaction_date,datetime64[ns],24,"[2024-01-01 00:00:00, 2024-02-01 00:00:00, 2024-03-01 00:00:00, 2024-04-01 00:00:00, 2024-05-01 00:00:00, 2024-06-01 00:00:00, 2024-07-01 00:00:00, 2024-08-01 00:00:00, 2024-09-01 00:00:00, 2024-10-01 00:00:00, 2024-11-01 00:00:00, 2024-12-01 00:00:00, 2025-01-01 00:00:00, 2025-02-01 00:00:00, 2025-03-01 00:00:00, 2025-04-01 00:00:00, 2025-05-01 00:00:00, 2025-06-01 00:00:00, 2025-07-01 00:00:00, 2025-08-01 00:00:00, 2025-09-01 00:00:00, 2025-10-01 00:00:00, 2025-11-01 00:00:00, 2025-12-01 00:00:00]"
transaction_quarters,int64,4,"[1, 2, 3, 4]"
transaction_month,object,12,"[January, February, March, April, May, June, July, August, September, October, November, December]"
transaction_day,object,7,"[Monday, Thursday, Friday, Wednesday, Saturday, Sunday, Tuesday]"
sale_price,float64,9998,"[300385.62, 208930.81, 218585.92, 246172.68, 212265.67, 275394.25, 310223.29, 356506.37, 212520.83, 407214.29, 269278.57, 216826.0, 237680.88, 240539.35, 230216.22, 222435.93, 199315.51, 285972.38, 179987.43, 166623.12, 233361.41, 211336.04, 347613.48, 336600.53, 487767.54, 232423.05, 322459.21, 399122.68, 328475.64, 347062.19, 372242.47, 384462.57, 237620.45, 261991.1, 231461.08, 339117.71, 165522.54, 251478.61, 392174.2, 188979.3, 212960.69, 184000.39, 194033.05, 184956.85, 274454.31, 227511.01, 523288.27, 507842.87, 418864.27, 223964.08, 313123.78, 465488.76, 483760.31, 496217.67, 201554.99, 362974.97, 340373.72, 344306.6, 337252.59, 311723.42, 191398.42, 221686.72, 199377.29, 485657.59, 535383.27, 197039.82, 231937.37, 203633.01, 163682.2, 314372.82, 361782.84, 245282.25, 227392.48, 375891.04, 237580.39, 208271.84, 331813.63, 199964.39, 255632.56, 384762.61, 194477.8, 223528.63, 337065.29, 376083.68, 221020.03, 375142.73, 353361.5, 532909.35, 442306.09, 495478.74, 353529.48, 443089.55, 470821.82, 495465.48, 242144.72, 253171.59, 241164.92, 202489.6, 242054.22, 330997.32, ...]"
price_segment,object,3,"[Mid-market, Budget, Premium]"
listing_status,object,2,"[Sold, Available]"
client_id,object,2000,"[C0027, C0097, C0113, C0141, C0146, C0023, C0040, C0007, C0082, C0038, C0107, nan, C0049, C0161, C0396, C1809, C1508, C1572, C0628, C0674, C0909, C0732, C1956, C0760, C0661, C1813, C0431, C0054, C1363, C1547, C0442, C1969, C0429, C1841, C0116, C1634, C1632, C1189, C0962, C0102, C1168, C1924, C1908, C0502, C1860, C0533, C0791, C0738, C0173, C1310, C1996, C1839, C0427, C0046, C0374, C0570, C1977, C0182, C1570, C0532, C1932, C0866, C1802, C0006, C1567, C0529, C1639, C0778, C1001, C1698, C1312, C0437, C1012, C1652, C1788, C1379, C1262, C1267, C0699, C0391, C1972, C0979, C1314, C0195, C0912, C1488, C1304, C1064, C0490, C1127, C0036, C0552, C1746, C0454, C1749, C1677, C0642, C1862, C0250, C1967, ...]"
client_type,object,2,"[Individual, nan, Company]"
date_of_birth,datetime64[ns],1889,"[1968-09-08 00:00:00, 1943-06-18 00:00:00, 1949-07-14 00:00:00, 1986-06-21 00:00:00, 1963-02-01 00:00:00, 1958-12-06 00:00:00, 1975-03-22 00:00:00, 1947-05-24 00:00:00, 1981-12-26 00:00:00, 1974-12-25 00:00:00, 1959-08-06 00:00:00, NaT, 1971-08-20 00:00:00, 1951-11-10 00:00:00, 2000-04-17 00:00:00, 1981-05-03 00:00:00, 1994-12-03 00:00:00, 1960-06-10 00:00:00, 1985-05-16 00:00:00, 1986-05-26 00:00:00, 1967-07-10 00:00:00, 1985-03-03 00:00:00, 1967-08-21 00:00:00, 1964-12-27 00:00:00, 1961-06-25 00:00:00, 1947-12-02 00:00:00, 1969-05-05 00:00:00, 1967-02-15 00:00:00, 1981-06-04 00:00:00, 1975-04-03 00:00:00, 1975-04-14 00:00:00, 1993-06-14 00:00:00, 1995-11-05 00:00:00, 1947-05-27 00:00:00, 1955-08-07 00:00:00, 1944-01-11 00:00:00, 1963-07-12 00:00:00, 1963-01-22 00:00:00, 1940-07-18 00:00:00, 1947-02-13 00:00:00, 1998-12-25 00:00:00, 1958-01-03 00:00:00, 1976-03-28 00:00:00, 1966-11-28 00:00:00, 1970-07-17 00:00:00, 1963-09-06 00:00:00, 1983-01-07 00:00:00, 1980-09-21 00:00:00, 1976-07-20 00:00:00, 1955-05-04 00:00:00, 1992-06-20 00:00:00, 1943-01-21 00:00:00, 1994-09-06 00:00:00, 1964-09-24 00:00:00, 1993-11-07 00:00:00, 1965-06-03 00:00:00, 1994-04-07 00:00:00, 1971-12-02 00:00:00, 1963-12-27 00:00:00, 1979-08-12 00:00:00, 1962-05-13 00:00:00, 1987-11-27 00:00:00, 1948-03-26 00:00:00, 1957-03-06 00:00:00, 1977-10-11 00:00:00, 1973-11-14 00:00:00, 1943-09-26 00:00:00, 1998-07-22 00:00:00, 1981-07-13 00:00:00, 1950-12-05 00:00:00, 1942-09-03 00:00:00, 1990-10-05 00:00:00, 1960-10-20 00:00:00, 1964-01-15 00:00:00, 1989-10-27 00:00:00, 1970-06-11 00:00:00, 1950-11-10 00:00:00, 1965-04-07 00:00:00, 1986-12-22 00:00:00, 1966-11-12 00:00:00, 1972-01-05 00:00:00, 1940-02-25 00:00:00, 1964-09-17 00:00:00, 1947-06-19 00:00:00, 1949-05-11 00:00:00, 1975-09-07 00:00:00, 1985-06-08 00:00:00, 1945-08-06 00:00:00, 1954-01-23 00:00:00, 1943-06-15 00:00:00, 1973-09-01 00:00:00, 1965-10-20 00:00:00, 1959-06-14 00:00:00, 1961-04-01 00:00:00, 1956-05-27 00:00:00, 1964-12-20 00:00:00, 1967-11-21 00:00:00, 1953-08-22 00:00:00, 1947-10-19 00:00:00, 1957-10-09 00:00:00, ...]"
age,float64,68,"[57.0, 83.0, 77.0, 40.0, 63.0, 67.0, 51.0, 79.0, 44.0, 66.0, nan, 54.0, 74.0, 26.0, 45.0, 31.0, 41.0, 59.0, 58.0, 61.0, 65.0, 78.0, 33.0, 30.0, 70.0, 82.0, 86.0, 27.0, 68.0, 50.0, 56.0, 62.0, 43.0, 71.0, 34.0, 32.0, 46.0, 64.0, 38.0, 69.0, 48.0, 52.0, 28.0, 75.0, 35.0, 36.0, 39.0, 80.0, 72.0, 60.0, 81.0, 47.0, 84.0, 76.0, 29.0, 42.0, 37.0, 49.0, 93.0, 73.0, 55.0, 85.0, 89.0, 94.0, 95.0, 87.0, 53.0, 25.0, 88.0]"
age_segment,object,3,"[Peak Earners, Retirees, nan, Young Professionals]"
gender,object,2,"[M, F, nan]"
country,object,10,"[USA, Canada, nan, UK, Australia, Germany, France, Belgium, Denmark, Russia, Mexico]"
region,object,57,"[California, Virginia, Utah, Colorado, Nevada, Quebec, nan, New York, Scotland, Queensland, British Columbia, Oregon, Manitoba, Hamburg, Georgia, Florida, Arizona, Texas, New South Wales, Occitanie, North Rhine-Westphalia, Ohio, Flanders, Brussels, Northern Ireland, Washington, England, Victoria, Wallonia, Alberta, Hesse, Wales, Ile-de-France, Wyoming, North Denmark, Bavaria, Krasnodar Krai, Berlin, Brittany, Zealand, Kansas, Ontario, Saint Petersburg, South Australia, Novosibirsk, Puebla, Mexico City, Nuevo Leon, Western Australia, Tatarstan, Jalisco, Capital Region, Normandy, Provence, Southern Denmark, Baja California, Central Denmark, Moscow Oblast]"
acquisition_purpose,object,2,"[Home, Investment, nan]"
satisfaction_score,float64,5,"[5.0, 4.0, 2.0, 3.0, nan, 1.0]"
loan_applied,object,2,"[Yes, No, nan]"
referral_channel,object,3,"[Website, Agency, Client, nan]"

---

### Dropping Columns

In [26]:
data = df.copy()

In [27]:
data.head()

,unit_category,tower_number,floor_area_sqft,size_segment,transaction_date,transaction_quarters,transaction_month,transaction_day,sale_price,price_segment,...,date_of_birth,age,age_segment,gender,country,region,acquisition_purpose,satisfaction_score,loan_applied,referral_channel
0,Apartment,1,1160.36,Standard,2024-01-01,1,January,Monday,300385.62,Mid-market,...,1968-09-08,57.0,Peak Earners,M,USA,California,Home,5.0,Yes,Website
1,Apartment,1,782.25,Compact,2024-01-01,1,January,Monday,208930.81,Budget,...,1943-06-18,83.0,Retirees,M,USA,Virginia,Home,5.0,Yes,Website
2,Apartment,1,756.21,Compact,2024-01-01,1,January,Monday,218585.92,Budget,...,1949-07-14,77.0,Retirees,M,USA,Utah,Investment,4.0,No,Agency
3,Apartment,1,743.09,Compact,2024-01-01,1,January,Monday,246172.68,Budget,...,1986-06-21,40.0,Peak Earners,F,USA,California,Home,5.0,No,Website
4,Apartment,2,701.66,Compact,2024-01-01,1,January,Monday,212265.67,Budget,...,1963-02-01,63.0,Retirees,M,USA,Colorado,Home,2.0,No,Website

In [28]:
data.isna().sum()

unit_category              0
tower_number               0
floor_area_sqft            0
size_segment               0
transaction_date           0
transaction_quarters       0
transaction_month          0
transaction_day            0
sale_price                 0
price_segment              0
listing_status             0
client_id               2695
client_type             2695
date_of_birth           2695
age                     2695
age_segment             2695
gender                  2695
country                 2695
region                  2695
acquisition_purpose     2695
satisfaction_score      2695
loan_applied            2695
referral_channel        2695
dtype: int64

In [29]:
data.drop(columns=['client_id','price_segment', 'size_segment', 'age_segment', 'transaction_date','date_of_birth','transaction_quarters','transaction_month','transaction_day','tower_number','listing_status'], inplace=True)

Observation : <br>
Above we removed the unnecessary features like segments coz they were the features which were made from another feature. And we also have removed feature `listing_status` coz as we removed all the rows containing null values, thus the rows that contained information for units not being sold were also removed. And hence the feature `listing_status` now only contained the values of property being sold. Since there was only values being left in the entire column, so it was a wise idea to drop the entire column.

In [30]:
data = data.dropna()

In [31]:
data.isna().sum()

unit_category          0
floor_area_sqft        0
sale_price             0
client_type            0
age                    0
gender                 0
country                0
region                 0
acquisition_purpose    0
satisfaction_score     0
loan_applied           0
referral_channel       0
dtype: int64

In [32]:
data.columns

Index(['unit_category', 'floor_area_sqft', 'sale_price', 'client_type', 'age',
       'gender', 'country', 'region', 'acquisition_purpose',
       'satisfaction_score', 'loan_applied', 'referral_channel'],
      dtype='object')

In [37]:
with pd.option_context('display.max_columns', None):
    display(data.head())

,unit_category,floor_area_sqft,sale_price,client_type,age,gender,country,region,acquisition_purpose,satisfaction_score,loan_applied,referral_channel
0,Apartment,1160.36,300385.62,Individual,57.0,M,USA,California,Home,5.0,Yes,Website
1,Apartment,782.25,208930.81,Individual,83.0,M,USA,Virginia,Home,5.0,Yes,Website
2,Apartment,756.21,218585.92,Individual,77.0,M,USA,Utah,Investment,4.0,No,Agency
3,Apartment,743.09,246172.68,Individual,40.0,F,USA,California,Home,5.0,No,Website
4,Apartment,701.66,212265.67,Individual,63.0,M,USA,Colorado,Home,2.0,No,Website

---

### Apllying Scaling and Encoding
- Scaling : Here we choose Standard scaler because there is no min and max limit to the `floor_area_sqft` and `sale_price`
    - For features like `satisfaction_score` MinMax Scaler will be used
- Encoding : Here we are choosing One Hot Encoding for `unit_category` and `listing_status`

In [39]:
from sklearn.preprocessing import StandardScaler, OneHotEncoder, MinMaxScaler
from sklearn.compose import ColumnTransformer

In [41]:
num_cols1 = ['sale_price', 'floor_area_sqft', 'age']
num_cols2 = ['satisfaction_score']
cat_cols = ['unit_category', 'client_type', 'gender', 'country', 
            'region', 'acquisition_purpose', 'loan_applied', 'referral_channel']

In [42]:
preprocessor = ColumnTransformer(transformers=[
    ('num1', StandardScaler(), num_cols1),
    ('num2', MinMaxScaler(), num_cols2),
    ('cat', OneHotEncoder(drop='first'), cat_cols)
])

data_processed = preprocessor.fit_transform(data)

In [ ]:
print(data_processed.shape)

data_processed

---

### Using KMeans for Clustering
Here we are directly using KMeans because we already know how many cluster (K) of buyer types we want. So instead of using Hierarchical Clustering we will proceed with KMeans Clustering.

In [ ]:
from sklearn.cluster import KMeans

In [ ]:
model = KMeans(
    n_clusters=4,
    init='k-means++',
    n_init=10,
    random_state=42
)

In [ ]:
prediction = model.fit_predict(data_processed)

In [ ]:
print(f"UNIQUE VALUES IN prediction : {np.unique(prediction)}")

Observation : <br>
Since we dont know which number belongs to which cluster type of buyers, so we need to put it with the dataset to recognise the different buyer type clusters. This process is called **`Cluster Profiling`**

---

### Putting The Predictions Back Into The Dataset

In [ ]:
data['buyer_type'] = prediction

Now we have to samples of different `Buyer Type`

In [ ]:
data[data['buyer_type'] == 0].head(10)

In [ ]:
data[data['buyer_type'] == 1].head(10)

In [ ]:
data[data['buyer_type'] == 2].head(10)

In [ ]:
data[data['buyer_type'] == 3].head(10)