In [2]:
%load_ext cudf.pandas
import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings('ignore')

In [3]:
df = pd.read_excel("/kaggle/input/datasets/ashura369/visualization-dataset/Visualisation Dataset.xlsx")

In [4]:
print(f"SHAPE OF THE DATASET : {df.shape}")

with pd.option_context('display.max_columns', None):
    display(df.sample(8))

SHAPE OF THE DATASET : (10000, 23)

,unit_category,tower_number,floor_area_sqft,size_segment,transaction_date,transaction_quarters,transaction_month,transaction_day,sale_price,price_segment,listing_status,client_id,client_type,date_of_birth,age,age_segment,gender,country,region,acquisition_purpose,satisfaction_score,loan_applied,referral_channel
8280,Apartment,16,549.98,Compact,2025-07-01,3,July,Tuesday,177362.74,Budget,Sold,C0810,Individual,1995-02-13,31.0,Peak Earners,M,USA,California,Home,1.0,Yes,Website
1527,Apartment,3,781.07,Compact,2024-04-01,2,April,Monday,225290.22,Budget,Sold,C0140,Individual,1952-06-18,74.0,Retirees,F,USA,California,Home,3.0,No,Website
6984,Office,20,856.15,Standard,2025-03-01,1,March,Saturday,257796.80,Budget,Sold,C0720,Individual,1981-05-17,45.0,Peak Earners,F,USA,California,Investment,1.0,Yes,Agency
5520,Apartment,2,649.69,Compact,2024-12-01,4,December,Sunday,225401.62,Budget,Sold,C0091,Individual,1959-11-13,66.0,Retirees,F,USA,California,Home,4.0,No,Website
9234,Office,13,1114.07,Standard,2025-10-01,4,October,Wednesday,357615.84,Mid-market,Sold,C1670,Individual,1970-12-09,55.0,Peak Earners,F,USA,Colorado,Home,3.0,Yes,Website
453,Office,18,1631.24,Spacious,2024-01-01,1,January,Monday,522844.12,Premium,Sold,C1109,Individual,1967-09-05,58.0,Peak Earners,F,USA,California,Home,1.0,Yes,Client
305,Apartment,13,1278.95,Spacious,2024-01-01,1,January,Monday,355143.03,Mid-market,Sold,C1529,Company,1989-04-19,37.0,Peak Earners,M,USA,California,Home,4.0,No,Website
120,Apartment,5,786.28,Compact,2024-01-01,1,January,Monday,246088.40,Budget,Available,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
pd.set_option('display.max_colwidth', None)          # Expands The DataFrame To Its Max Width

pd.DataFrame({
    'DATA TYPE' : df.dtypes,
    'NO. OF UNIQUE VALUES' : df.nunique(),
    'UNIQUE VALUES' : [df[i].unique() for i in df.columns]
})

,DATA TYPE,NO. OF UNIQUE VALUES,UNIQUE VALUES
unit_category,object,2,"[Apartment, Office]"
tower_number,int64,20,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]"
floor_area_sqft,float64,1208,"[1160.36, 782.25, 756.21, 743.09, 701.66, 927.8299999999999, 1109.25, 1132.06, 670.89, 1596.35, 781.07, 785.48, 798.5, 798.2800000000001, 748.06, 715.6700000000001, 788.73, 633.61, 740.75, 719.47, 1181.69, 1146.24, 1957.16, 740.8299999999999, 1201.5, 1146.11, 1154.92, 757.2, 753.2900000000001, 619.7800000000001, 1168.59, 613.59, 788.72, 1281.85, 715.54, 584.19, 788.7900000000001, 1625.05, 1397.4, 727.55, 943.48, 1577.79, 650.6700000000001, 1107.33, 931.4, 1118.94, 697.74, 708.3199999999999, 1617.9, 1604.8, 722.22, 689.75, 668.89, 744.01, 1125.84, 784.09, 802.97, 1122.15, 776.04, 765.56, 1117.14, 679.93, 733.4499999999999, 1343.96, 691.09, 1174.48, 693.8499999999999, 1179.42, 1607.94, 1588.14, 1353.02, 1615.98, 1630.82, 786.98, 789.38, 809.06, 760.39, 780.6800000000001, 1294.91, 801.66, 1110.99, 1307.35, 734.73, 779.87, 1160.48, 800.23, 805.88, 802.11, 799.1, 775.8499999999999, 793.56, 629.2700000000001, 624.9599999999999, 804.8399999999999, 1006.65, 1278.6, 786.2800000000001, 1051.39, 1787.13, 627.56, ...]"
size_segment,object,3,"[Standard, Compact, Spacious]"
transaction_date,datetime64[ns],24,"[2024-01-01 00:00:00, 2024-02-01 00:00:00, 2024-03-01 00:00:00, 2024-04-01 00:00:00, 2024-05-01 00:00:00, 2024-06-01 00:00:00, 2024-07-01 00:00:00, 2024-08-01 00:00:00, 2024-09-01 00:00:00, 2024-10-01 00:00:00, 2024-11-01 00:00:00, 2024-12-01 00:00:00, 2025-01-01 00:00:00, 2025-02-01 00:00:00, 2025-03-01 00:00:00, 2025-04-01 00:00:00, 2025-05-01 00:00:00, 2025-06-01 00:00:00, 2025-07-01 00:00:00, 2025-08-01 00:00:00, 2025-09-01 00:00:00, 2025-10-01 00:00:00, 2025-11-01 00:00:00, 2025-12-01 00:00:00]"
transaction_quarters,int64,4,"[1, 2, 3, 4]"
transaction_month,object,12,"[January, February, March, April, May, June, July, August, September, October, November, December]"
transaction_day,object,7,"[Monday, Thursday, Friday, Wednesday, Saturday, Sunday, Tuesday]"
sale_price,float64,9998,"[300385.62, 208930.81, 218585.92, 246172.68, 212265.67, 275394.25, 310223.29, 356506.37, 212520.83, 407214.29, 269278.57, 216826.0, 237680.88, 240539.35, 230216.22, 222435.93, 199315.51, 285972.38, 179987.43, 166623.12, 233361.41, 211336.04, 347613.48, 336600.53, 487767.54, 232423.05, 322459.21, 399122.68, 328475.64, 347062.19, 372242.47, 384462.57, 237620.45, 261991.1, 231461.08, 339117.71, 165522.54, 251478.61, 392174.2, 188979.3, 212960.69, 184000.39, 194033.05, 184956.85, 274454.31, 227511.01, 523288.27, 507842.87, 418864.27, 223964.08, 313123.78, 465488.76, 483760.31, 496217.67, 201554.99, 362974.97, 340373.72, 344306.6, 337252.59, 311723.42, 191398.42, 221686.72, 199377.29, 485657.59, 535383.27, 197039.82, 231937.37, 203633.01, 163682.2, 314372.82, 361782.84, 245282.25, 227392.48, 375891.04, 237580.39, 208271.84, 331813.63, 199964.39, 255632.56, 384762.61, 194477.8, 223528.63, 337065.29, 376083.68, 221020.03, 375142.73, 353361.5, 532909.35, 442306.09, 495478.74, 353529.48, 443089.55, 470821.82, 495465.48, 242144.72, 253171.59, 241164.92, 202489.6, 242054.22, 330997.32, ...]"
price_segment,object,3,"[Mid-market, Budget, Premium]"
listing_status,object,2,"[Sold, Available]"
client_id,object,2000,"[C0027, C0097, C0113, C0141, C0146, C0023, C0040, C0007, C0082, C0038, C0107, nan, C0049, C0161, C0396, C1809, C1508, C1572, C0628, C0674, C0909, C0732, C1956, C0760, C0661, C1813, C0431, C0054, C1363, C1547, C0442, C1969, C0429, C1841, C0116, C1634, C1632, C1189, C0962, C0102, C1168, C1924, C1908, C0502, C1860, C0533, C0791, C0738, C0173, C1310, C1996, C1839, C0427, C0046, C0374, C0570, C1977, C0182, C1570, C0532, C1932, C0866, C1802, C0006, C1567, C0529, C1639, C0778, C1001, C1698, C1312, C0437, C1012, C1652, C1788, C1379, C1262, C1267, C0699, C0391, C1972, C0979, C1314, C0195, C0912, C1488, C1304, C1064, C0490, C1127, C0036, C0552, C1746, C0454, C1749, C1677, C0642, C1862, C0250, C1967, ...]"
client_type,object,2,"[Individual, nan, Company]"
date_of_birth,datetime64[ns],1889,"[1968-09-08 00:00:00, 1943-06-18 00:00:00, 1949-07-14 00:00:00, 1986-06-21 00:00:00, 1963-02-01 00:00:00, 1958-12-06 00:00:00, 1975-03-22 00:00:00, 1947-05-24 00:00:00, 1981-12-26 00:00:00, 1974-12-25 00:00:00, 1959-08-06 00:00:00, NaT, 1971-08-20 00:00:00, 1951-11-10 00:00:00, 2000-04-17 00:00:00, 1981-05-03 00:00:00, 1994-12-03 00:00:00, 1960-06-10 00:00:00, 1985-05-16 00:00:00, 1986-05-26 00:00:00, 1967-07-10 00:00:00, 1985-03-03 00:00:00, 1967-08-21 00:00:00, 1964-12-27 00:00:00, 1961-06-25 00:00:00, 1947-12-02 00:00:00, 1969-05-05 00:00:00, 1967-02-15 00:00:00, 1981-06-04 00:00:00, 1975-04-03 00:00:00, 1975-04-14 00:00:00, 1993-06-14 00:00:00, 1995-11-05 00:00:00, 1947-05-27 00:00:00, 1955-08-07 00:00:00, 1944-01-11 00:00:00, 1963-07-12 00:00:00, 1963-01-22 00:00:00, 1940-07-18 00:00:00, 1947-02-13 00:00:00, 1998-12-25 00:00:00, 1958-01-03 00:00:00, 1976-03-28 00:00:00, 1966-11-28 00:00:00, 1970-07-17 00:00:00, 1963-09-06 00:00:00, 1983-01-07 00:00:00, 1980-09-21 00:00:00, 1976-07-20 00:00:00, 1955-05-04 00:00:00, 1992-06-20 00:00:00, 1943-01-21 00:00:00, 1994-09-06 00:00:00, 1964-09-24 00:00:00, 1993-11-07 00:00:00, 1965-06-03 00:00:00, 1994-04-07 00:00:00, 1971-12-02 00:00:00, 1963-12-27 00:00:00, 1979-08-12 00:00:00, 1962-05-13 00:00:00, 1987-11-27 00:00:00, 1948-03-26 00:00:00, 1957-03-06 00:00:00, 1977-10-11 00:00:00, 1973-11-14 00:00:00, 1943-09-26 00:00:00, 1998-07-22 00:00:00, 1981-07-13 00:00:00, 1950-12-05 00:00:00, 1942-09-03 00:00:00, 1990-10-05 00:00:00, 1960-10-20 00:00:00, 1964-01-15 00:00:00, 1989-10-27 00:00:00, 1970-06-11 00:00:00, 1950-11-10 00:00:00, 1965-04-07 00:00:00, 1986-12-22 00:00:00, 1966-11-12 00:00:00, 1972-01-05 00:00:00, 1940-02-25 00:00:00, 1964-09-17 00:00:00, 1947-06-19 00:00:00, 1949-05-11 00:00:00, 1975-09-07 00:00:00, 1985-06-08 00:00:00, 1945-08-06 00:00:00, 1954-01-23 00:00:00, 1943-06-15 00:00:00, 1973-09-01 00:00:00, 1965-10-20 00:00:00, 1959-06-14 00:00:00, 1961-04-01 00:00:00, 1956-05-27 00:00:00, 1964-12-20 00:00:00, 1967-11-21 00:00:00, 1953-08-22 00:00:00, 1947-10-19 00:00:00, 1957-10-09 00:00:00, ...]"
age,float64,68,"[57.0, 83.0, 77.0, 40.0, 63.0, 67.0, 51.0, 79.0, 44.0, 66.0, nan, 54.0, 74.0, 26.0, 45.0, 31.0, 41.0, 59.0, 58.0, 61.0, 65.0, 78.0, 33.0, 30.0, 70.0, 82.0, 86.0, 27.0, 68.0, 50.0, 56.0, 62.0, 43.0, 71.0, 34.0, 32.0, 46.0, 64.0, 38.0, 69.0, 48.0, 52.0, 28.0, 75.0, 35.0, 36.0, 39.0, 80.0, 72.0, 60.0, 81.0, 47.0, 84.0, 76.0, 29.0, 42.0, 37.0, 49.0, 93.0, 73.0, 55.0, 85.0, 89.0, 94.0, 95.0, 87.0, 53.0, 25.0, 88.0]"
age_segment,object,3,"[Peak Earners, Retirees, nan, Young Professionals]"
gender,object,2,"[M, F, nan]"
country,object,10,"[USA, Canada, nan, UK, Australia, Germany, France, Belgium, Denmark, Russia, Mexico]"
region,object,57,"[California, Virginia, Utah, Colorado, Nevada, Quebec, nan, New York, Scotland, Queensland, British Columbia, Oregon, Manitoba, Hamburg, Georgia, Florida, Arizona, Texas, New South Wales, Occitanie, North Rhine-Westphalia, Ohio, Flanders, Brussels, Northern Ireland, Washington, England, Victoria, Wallonia, Alberta, Hesse, Wales, Ile-de-France, Wyoming, North Denmark, Bavaria, Krasnodar Krai, Berlin, Brittany, Zealand, Kansas, Ontario, Saint Petersburg, South Australia, Novosibirsk, Puebla, Mexico City, Nuevo Leon, Western Australia, Tatarstan, Jalisco, Capital Region, Normandy, Provence, Southern Denmark, Baja California, Central Denmark, Moscow Oblast]"
acquisition_purpose,object,2,"[Home, Investment, nan]"
satisfaction_score,float64,5,"[5.0, 4.0, 2.0, 3.0, nan, 1.0]"
loan_applied,object,2,"[Yes, No, nan]"
referral_channel,object,3,"[Website, Agency, Client, nan]"

---

### Dropping Columns

In [6]:
data = df.copy()

In [7]:
data.head()

,unit_category,tower_number,floor_area_sqft,size_segment,transaction_date,transaction_quarters,transaction_month,transaction_day,sale_price,price_segment,...,date_of_birth,age,age_segment,gender,country,region,acquisition_purpose,satisfaction_score,loan_applied,referral_channel
0,Apartment,1,1160.36,Standard,2024-01-01,1,January,Monday,300385.62,Mid-market,...,1968-09-08,57.0,Peak Earners,M,USA,California,Home,5.0,Yes,Website
1,Apartment,1,782.25,Compact,2024-01-01,1,January,Monday,208930.81,Budget,...,1943-06-18,83.0,Retirees,M,USA,Virginia,Home,5.0,Yes,Website
2,Apartment,1,756.21,Compact,2024-01-01,1,January,Monday,218585.92,Budget,...,1949-07-14,77.0,Retirees,M,USA,Utah,Investment,4.0,No,Agency
3,Apartment,1,743.09,Compact,2024-01-01,1,January,Monday,246172.68,Budget,...,1986-06-21,40.0,Peak Earners,F,USA,California,Home,5.0,No,Website
4,Apartment,2,701.66,Compact,2024-01-01,1,January,Monday,212265.67,Budget,...,1963-02-01,63.0,Retirees,M,USA,Colorado,Home,2.0,No,Website

In [8]:
data.isna().sum()

unit_category              0
tower_number               0
floor_area_sqft            0
size_segment               0
transaction_date           0
transaction_quarters       0
transaction_month          0
transaction_day            0
sale_price                 0
price_segment              0
listing_status             0
client_id               2695
client_type             2695
date_of_birth           2695
age                     2695
age_segment             2695
gender                  2695
country                 2695
region                  2695
acquisition_purpose     2695
satisfaction_score      2695
loan_applied            2695
referral_channel        2695
dtype: int64

In [9]:
data.drop(columns=['client_id','price_segment', 'size_segment', 'age_segment', 'transaction_date','date_of_birth','transaction_quarters','transaction_month','transaction_day','tower_number','listing_status'], inplace=True)

Observation : <br>
Above we removed the unnecessary features like segments coz they were the features which were made from another feature. And we also have removed feature `listing_status` coz as we removed all the rows containing null values, thus the rows that contained information for units not being sold were also removed. And hence the feature `listing_status` now only contained the values of property being sold. Since there was only values being left in the entire column, so it was a wise idea to drop the entire column.

In [10]:
data = data.dropna()

In [11]:
data.isna().sum()

unit_category          0
floor_area_sqft        0
sale_price             0
client_type            0
age                    0
gender                 0
country                0
region                 0
acquisition_purpose    0
satisfaction_score     0
loan_applied           0
referral_channel       0
dtype: int64

In [12]:
data.columns

Index(['unit_category', 'floor_area_sqft', 'sale_price', 'client_type', 'age',
       'gender', 'country', 'region', 'acquisition_purpose',
       'satisfaction_score', 'loan_applied', 'referral_channel'],
      dtype='object')

In [13]:
with pd.option_context('display.max_columns', None):
    display(data.head())

,unit_category,floor_area_sqft,sale_price,client_type,age,gender,country,region,acquisition_purpose,satisfaction_score,loan_applied,referral_channel
0,Apartment,1160.36,300385.62,Individual,57.0,M,USA,California,Home,5.0,Yes,Website
1,Apartment,782.25,208930.81,Individual,83.0,M,USA,Virginia,Home,5.0,Yes,Website
2,Apartment,756.21,218585.92,Individual,77.0,M,USA,Utah,Investment,4.0,No,Agency
3,Apartment,743.09,246172.68,Individual,40.0,F,USA,California,Home,5.0,No,Website
4,Apartment,701.66,212265.67,Individual,63.0,M,USA,Colorado,Home,2.0,No,Website

---

### Apllying Scaling and Encoding
- Scaling : Here we choose Standard scaler because there is no min and max limit to the `floor_area_sqft` and `sale_price`
    - For features like `satisfaction_score` MinMax Scaler will be used
- Encoding : Here we are choosing One Hot Encoding for `unit_category` and `listing_status`

In [14]:
from sklearn.preprocessing import StandardScaler, OneHotEncoder, MinMaxScaler
from sklearn.compose import ColumnTransformer

Using Frequency Encode the high-cardinality columns

In [15]:
# We map the country and region to how often they appear in the data
data['country_freq'] = data['country'].map(data['country'].value_counts())
data['region_freq'] = data['region'].map(data['region'].value_counts())

In [16]:
# Notice that we added 'country_freq' and 'region_freq' here as numbers!
num_cols1 = ['sale_price', 'floor_area_sqft', 'age', 'country_freq', 'region_freq']
num_cols2 = ['satisfaction_score']

# Notice that we REMOVED the original 'country' and 'region' from here!
cat_cols = ['unit_category', 'client_type', 'gender', 
            'acquisition_purpose', 'loan_applied', 'referral_channel']

In [17]:
transform = ColumnTransformer(transformers=[
    ('num1', StandardScaler(), num_cols1),
    ('num2', MinMaxScaler(), num_cols2),
    ('cat', OneHotEncoder(drop='first', handle_unknown='ignore'), cat_cols)
])

In [18]:
data_processed = transform.fit_transform(data)

In [19]:
print(data_processed.shape)

data_processed

(7305, 13)

array([[-0.33841851,  0.04582912,  0.05725728, ...,  1.        ,
         0.        ,  1.        ],
       [-1.03102328, -0.85612298,  1.56430751, ...,  1.        ,
         0.        ,  1.        ],
       [-0.95790329, -0.91823938,  1.21652669, ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [ 0.45109994,  0.20596253, -1.73961031, ...,  0.        ,
         0.        ,  0.        ],
       [-0.60498689, -0.66874804, -0.87015825, ...,  0.        ,
         0.        ,  0.        ],
       [-0.43078024, -0.66874804, -1.27590255, ...,  0.        ,
         0.        ,  1.        ]])

---

### Using KMeans for Clustering
Here we are directly using KMeans because we already know how many cluster (K) of buyer types we want. So instead of using Hierarchical Clustering we will proceed with KMeans Clustering.

In [20]:
from sklearn.cluster import KMeans

In [21]:
model = KMeans(
    n_clusters=4,
    init='k-means++',
    n_init=10,
    random_state=42
)

In [22]:
prediction = model.fit_predict(data_processed)

In [23]:
print(f"UNIQUE VALUES IN prediction : {np.unique(prediction)}")

UNIQUE VALUES IN prediction : [0 1 2 3]

Observation : <br>
Since we dont know which number belongs to which cluster type of buyers, so we need to put it with the dataset to recognise the different buyer type clusters. This process is called **`Cluster Profiling`**

---

### Putting The Predictions Back Into The Dataset

In [24]:
sold_units = df['listing_status'] == 'Sold'

df.loc[sold_units, 'buyers_type'] = prediction

Replacing the `NaN` values in feature `buyers_type`

In [25]:
df['buyers_type'] = df['buyers_type'].fillna('NO BUYERS')

---

In [26]:
with pd.option_context('display.max_columns', None):
    display(df)

,unit_category,tower_number,floor_area_sqft,size_segment,transaction_date,transaction_quarters,transaction_month,transaction_day,sale_price,price_segment,listing_status,client_id,client_type,date_of_birth,age,age_segment,gender,country,region,acquisition_purpose,satisfaction_score,loan_applied,referral_channel,buyers_type
0,Apartment,1,1160.36,Standard,2024-01-01,1,January,Monday,300385.62,Mid-market,Sold,C0027,Individual,1968-09-08,57.0,Peak Earners,M,USA,California,Home,5.0,Yes,Website,0.0
1,Apartment,1,782.25,Compact,2024-01-01,1,January,Monday,208930.81,Budget,Sold,C0097,Individual,1943-06-18,83.0,Retirees,M,USA,Virginia,Home,5.0,Yes,Website,1.0
2,Apartment,1,756.21,Compact,2024-01-01,1,January,Monday,218585.92,Budget,Sold,C0113,Individual,1949-07-14,77.0,Retirees,M,USA,Utah,Investment,4.0,No,Agency,1.0
3,Apartment,1,743.09,Compact,2024-01-01,1,January,Monday,246172.68,Budget,Sold,C0141,Individual,1986-06-21,40.0,Peak Earners,F,USA,California,Home,5.0,No,Website,0.0
4,Apartment,2,701.66,Compact,2024-01-01,1,January,Monday,212265.67,Budget,Sold,C0146,Individual,1963-02-01,63.0,Retirees,M,USA,Colorado,Home,2.0,No,Website,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,Apartment,20,860.80,Standard,2025-12-01,4,December,Monday,271177.34,Budget,Available,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NO BUYERS
9996,Apartment,20,860.80,Standard,2025-12-01,4,December,Monday,265186.67,Budget,Sold,C1412,Company,1985-06-28,41.0,Peak Earners,F,USA,Nevada,Home,2.0,No,Agency,1.0
9997,Apartment,20,860.80,Standard,2025-12-01,4,December,Monday,288189.74,Mid-market,Sold,C0504,Individual,1992-01-14,34.0,Peak Earners,M,USA,Utah,Home,2.0,No,Website,1.0
9998,Apartment,20,1062.33,Standard,2025-12-01,4,December,Monday,328980.19,Mid-market,Available,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NO BUYERS
9999,Apartment,4,733.19,Compact,2025-12-01,4,December,Monday,217357.63,Budget,Available,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NO BUYERS

In [27]:
df[['satisfaction_score', 'age']] = df[['satisfaction_score', 'age']].astype('Int64')

---

### Naming The Clusters 
To do so first we must have to plot the different values of `buyers_type` and analyze them.

In [28]:
with pd.option_context('display.max_columns', None):
    display(df[df['buyers_type'] == 0].head(10))

,unit_category,tower_number,floor_area_sqft,size_segment,transaction_date,transaction_quarters,transaction_month,transaction_day,sale_price,price_segment,listing_status,client_id,client_type,date_of_birth,age,age_segment,gender,country,region,acquisition_purpose,satisfaction_score,loan_applied,referral_channel,buyers_type
0,Apartment,1,1160.36,Standard,2024-01-01,1,January,Monday,300385.62,Mid-market,Sold,C0027,Individual,1968-09-08,57,Peak Earners,M,USA,California,Home,5,Yes,Website,0.0
3,Apartment,1,743.09,Compact,2024-01-01,1,January,Monday,246172.68,Budget,Sold,C0141,Individual,1986-06-21,40,Peak Earners,F,USA,California,Home,5,No,Website,0.0
5,Apartment,2,927.83,Standard,2024-01-01,1,January,Monday,275394.25,Budget,Sold,C0023,Individual,1958-12-06,67,Retirees,M,USA,California,Home,3,Yes,Website,0.0
10,Apartment,3,781.07,Compact,2024-01-01,1,January,Monday,269278.57,Budget,Sold,C0107,Individual,1959-08-06,66,Retirees,M,USA,California,Home,4,Yes,Agency,0.0
13,Apartment,5,798.28,Compact,2024-01-01,1,January,Monday,240539.35,Budget,Sold,C0049,Individual,1971-08-20,54,Peak Earners,F,USA,California,Home,1,No,Website,0.0
14,Apartment,5,798.28,Compact,2024-01-01,1,January,Monday,230216.22,Budget,Sold,C0161,Individual,1951-11-10,74,Retirees,M,USA,California,Home,5,No,Website,0.0
22,Apartment,1,1181.69,Standard,2024-01-01,1,January,Monday,347613.48,Mid-market,Sold,C0674,Individual,1986-05-26,40,Peak Earners,F,USA,California,Investment,4,No,Website,0.0
23,Apartment,1,1146.24,Standard,2024-01-01,1,January,Monday,336600.53,Mid-market,Sold,C0909,Individual,1967-07-10,59,Peak Earners,M,USA,California,Investment,1,Yes,Agency,0.0
26,Apartment,1,1201.50,Spacious,2024-01-01,1,January,Monday,322459.21,Mid-market,Sold,C0760,Individual,1964-12-27,61,Retirees,F,USA,California,Investment,3,No,Website,0.0
30,Apartment,1,1154.92,Standard,2024-01-01,1,January,Monday,372242.47,Mid-market,Sold,C0431,Individual,1969-05-05,57,Peak Earners,M,USA,California,Home,5,Yes,Website,0.0

In [29]:
with pd.option_context('display.max_columns', None):
    display(df[df['buyers_type'] == 1].head(10))

,unit_category,tower_number,floor_area_sqft,size_segment,transaction_date,transaction_quarters,transaction_month,transaction_day,sale_price,price_segment,listing_status,client_id,client_type,date_of_birth,age,age_segment,gender,country,region,acquisition_purpose,satisfaction_score,loan_applied,referral_channel,buyers_type
1,Apartment,1,782.25,Compact,2024-01-01,1,January,Monday,208930.81,Budget,Sold,C0097,Individual,1943-06-18,83,Retirees,M,USA,Virginia,Home,5,Yes,Website,1.0
2,Apartment,1,756.21,Compact,2024-01-01,1,January,Monday,218585.92,Budget,Sold,C0113,Individual,1949-07-14,77,Retirees,M,USA,Utah,Investment,4,No,Agency,1.0
4,Apartment,2,701.66,Compact,2024-01-01,1,January,Monday,212265.67,Budget,Sold,C0146,Individual,1963-02-01,63,Retirees,M,USA,Colorado,Home,2,No,Website,1.0
6,Apartment,2,1109.25,Standard,2024-01-01,1,January,Monday,310223.29,Mid-market,Sold,C0040,Individual,1975-03-22,51,Peak Earners,M,USA,Nevada,Home,5,No,Website,1.0
8,Apartment,3,670.89,Compact,2024-01-01,1,January,Monday,212520.83,Budget,Sold,C0082,Individual,1981-12-26,44,Peak Earners,F,USA,Virginia,Investment,5,No,Client,1.0
15,Apartment,1,748.06,Compact,2024-01-01,1,January,Monday,222435.93,Budget,Sold,C0396,Individual,2000-04-17,26,Young Professionals,M,USA,Nevada,Home,5,No,Agency,1.0
16,Apartment,1,715.67,Compact,2024-01-01,1,January,Monday,199315.51,Budget,Sold,C1809,Individual,1981-05-03,45,Peak Earners,F,USA,New York,Home,4,Yes,Agency,1.0
25,Office,1,740.83,Compact,2024-01-01,1,January,Monday,232423.05,Budget,Sold,C1956,Individual,1967-08-21,58,Peak Earners,F,USA,Oregon,Home,2,No,Agency,1.0
31,Apartment,1,1154.92,Standard,2024-01-01,1,January,Monday,384462.57,Mid-market,Sold,C0054,Company,1967-02-15,59,Peak Earners,M,USA,Nevada,Investment,5,No,Website,1.0
32,Apartment,1,757.20,Compact,2024-01-01,1,January,Monday,237620.45,Budget,Sold,C1363,Individual,1981-06-04,45,Peak Earners,M,USA,Georgia,Home,5,Yes,Agency,1.0

In [30]:
with pd.option_context('display.max_columns', None):
    display(df[df['buyers_type'] == 2].head(10))

,unit_category,tower_number,floor_area_sqft,size_segment,transaction_date,transaction_quarters,transaction_month,transaction_day,sale_price,price_segment,listing_status,client_id,client_type,date_of_birth,age,age_segment,gender,country,region,acquisition_purpose,satisfaction_score,loan_applied,referral_channel,buyers_type
7,Apartment,3,1132.06,Standard,2024-01-01,1,January,Monday,356506.37,Mid-market,Sold,C0007,Individual,1947-05-24,79,Retirees,M,Canada,Quebec,Investment,5,No,Website,2.0
17,Apartment,1,788.73,Compact,2024-01-01,1,January,Monday,285972.38,Budget,Sold,C1508,Individual,1994-12-03,31,Peak Earners,M,UK,Scotland,Home,3,No,Agency,2.0
18,Apartment,1,633.61,Compact,2024-01-01,1,January,Monday,179987.43,Budget,Sold,C1572,Individual,1960-06-10,66,Retirees,M,Australia,Queensland,Home,3,No,Agency,2.0
21,Office,1,719.47,Compact,2024-01-01,1,January,Monday,211336.04,Budget,Sold,C0628,Individual,1985-05-16,41,Peak Earners,M,Canada,British Columbia,Home,3,Yes,Agency,2.0
28,Apartment,1,1146.11,Standard,2024-01-01,1,January,Monday,328475.64,Mid-market,Sold,C0661,Individual,1961-06-25,65,Retirees,F,Canada,Manitoba,Home,3,No,Website,2.0
29,Office,1,1146.11,Standard,2024-01-01,1,January,Monday,347062.19,Mid-market,Sold,C1813,Individual,1947-12-02,78,Retirees,M,Germany,Hamburg,Investment,3,Yes,Website,2.0
49,Apartment,2,727.55,Compact,2024-01-01,1,January,Monday,223964.08,Budget,Sold,C1168,Individual,1998-12-25,27,Young Professionals,F,Germany,Hamburg,Home,2,Yes,Agency,2.0
66,Apartment,3,689.75,Compact,2024-01-01,1,January,Monday,231937.37,Budget,Sold,C0374,Individual,1993-11-07,32,Peak Earners,F,Australia,New South Wales,Investment,4,Yes,Agency,2.0
67,Apartment,3,668.89,Compact,2024-01-01,1,January,Monday,203633.01,Budget,Sold,C0570,Individual,1965-06-03,61,Retirees,F,France,Occitanie,Home,5,Yes,Website,2.0
70,Apartment,3,1125.84,Standard,2024-01-01,1,January,Monday,361782.84,Mid-market,Sold,C0182,Individual,1971-12-02,54,Peak Earners,F,Germany,North Rhine-Westphalia,Investment,1,Yes,Website,2.0

In [31]:
with pd.option_context('display.max_columns', None):
    display(df[df['buyers_type'] == 3].head(10))

,unit_category,tower_number,floor_area_sqft,size_segment,transaction_date,transaction_quarters,transaction_month,transaction_day,sale_price,price_segment,listing_status,client_id,client_type,date_of_birth,age,age_segment,gender,country,region,acquisition_purpose,satisfaction_score,loan_applied,referral_channel,buyers_type
9,Apartment,3,1596.35,Spacious,2024-01-01,1,January,Monday,407214.29,Mid-market,Sold,C0038,Individual,1974-12-25,51,Peak Earners,F,USA,California,Investment,4,No,Client,3.0
24,Apartment,1,1957.16,Spacious,2024-01-01,1,January,Monday,487767.54,Premium,Sold,C0732,Individual,1985-03-03,41,Peak Earners,M,USA,Oregon,Home,5,No,Website,3.0
46,Apartment,2,1625.05,Spacious,2024-01-01,1,January,Monday,523288.27,Premium,Sold,C0962,Individual,1940-07-18,86,Retirees,M,USA,California,Home,4,No,Website,3.0
47,Apartment,2,1625.05,Spacious,2024-01-01,1,January,Monday,507842.87,Premium,Sold,C0040,Individual,1975-03-22,51,Peak Earners,M,USA,Nevada,Home,5,No,Website,3.0
48,Apartment,2,1397.40,Spacious,2024-01-01,1,January,Monday,418864.27,Mid-market,Sold,C0102,Individual,1947-02-13,79,Retirees,M,USA,California,Investment,5,Yes,Website,3.0
51,Apartment,2,1577.79,Spacious,2024-01-01,1,January,Monday,465488.76,Premium,Sold,C1908,Individual,1976-03-28,50,Peak Earners,F,USA,California,Home,2,No,Website,3.0
52,Apartment,2,1577.79,Spacious,2024-01-01,1,January,Monday,483760.31,Premium,Sold,C0502,Individual,1966-11-28,59,Peak Earners,F,USA,Arizona,Home,4,No,Website,3.0
53,Apartment,2,1577.79,Spacious,2024-01-01,1,January,Monday,496217.67,Premium,Sold,C1860,Company,1970-07-17,56,Peak Earners,F,USA,California,Home,4,Yes,Agency,3.0
63,Apartment,2,1617.90,Spacious,2024-01-01,1,January,Monday,485657.59,Premium,Sold,C0427,Individual,1994-09-06,31,Peak Earners,F,USA,California,Home,4,Yes,Website,3.0
79,Office,3,1343.96,Spacious,2024-01-01,1,January,Monday,384762.61,Mid-market,Sold,C1567,Individual,1977-10-11,48,Peak Earners,M,USA,Georgia,Home,4,No,Client,3.0

Observation :

**Cluster Profiling**

After running the K-Means algorithm, we analyzed the statistical averages of each group to assign them to our target Business Segments:

* **Cluster 3 = Luxury Investors (C4)**
  * This cluster has the highest average `sale_price` ($492,615) and the largest `floor_area_sqft` (1,612 sqft). They also have the highest satisfaction score (3.07). This perfectly matches the "High satisfaction, large investments" criteria!
  
* **Cluster 2 = First-Time Buyers (C2)**
  * This cluster has the absolute youngest average `age` (54.3 years old) across the entire dataset, and they have one of the highest `loan_applied` rates. This perfectly matches the "Younger, loan dependent" criteria!
  
* **Cluster 0 = Global Investors (C1)**
  * This cluster targets standard-sized apartments (avg 892 sqft) for solid rental yield investments.
  
* **Cluster 1 = Corporate Buyers (C3)**
  * This cluster targets compact units (avg 857 sqft), which are highly characteristic of companies buying smaller units for corporate housing or short-term employee stays.

### Renaming The Cluster Values

In [32]:
val = {
    0 : 'Global Investors',
    1 : 'Corporate Buyers',
    2 : 'First Time Buyers',
    3 : 'Luxury Investors'
}

df['buyers_type'] = df['buyers_type'].map(val)

In [33]:
with pd.option_context('display.max_columns', None):
    display(df)

,unit_category,tower_number,floor_area_sqft,size_segment,transaction_date,transaction_quarters,transaction_month,transaction_day,sale_price,price_segment,listing_status,client_id,client_type,date_of_birth,age,age_segment,gender,country,region,acquisition_purpose,satisfaction_score,loan_applied,referral_channel,buyers_type
0,Apartment,1,1160.36,Standard,2024-01-01,1,January,Monday,300385.62,Mid-market,Sold,C0027,Individual,1968-09-08,57,Peak Earners,M,USA,California,Home,5,Yes,Website,Global Investors
1,Apartment,1,782.25,Compact,2024-01-01,1,January,Monday,208930.81,Budget,Sold,C0097,Individual,1943-06-18,83,Retirees,M,USA,Virginia,Home,5,Yes,Website,Corporate Buyers
2,Apartment,1,756.21,Compact,2024-01-01,1,January,Monday,218585.92,Budget,Sold,C0113,Individual,1949-07-14,77,Retirees,M,USA,Utah,Investment,4,No,Agency,Corporate Buyers
3,Apartment,1,743.09,Compact,2024-01-01,1,January,Monday,246172.68,Budget,Sold,C0141,Individual,1986-06-21,40,Peak Earners,F,USA,California,Home,5,No,Website,Global Investors
4,Apartment,2,701.66,Compact,2024-01-01,1,January,Monday,212265.67,Budget,Sold,C0146,Individual,1963-02-01,63,Retirees,M,USA,Colorado,Home,2,No,Website,Corporate Buyers
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,Apartment,20,860.80,Standard,2025-12-01,4,December,Monday,271177.34,Budget,Available,NaN,NaN,NaT,<NA>,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN
9996,Apartment,20,860.80,Standard,2025-12-01,4,December,Monday,265186.67,Budget,Sold,C1412,Company,1985-06-28,41,Peak Earners,F,USA,Nevada,Home,2,No,Agency,Corporate Buyers
9997,Apartment,20,860.80,Standard,2025-12-01,4,December,Monday,288189.74,Mid-market,Sold,C0504,Individual,1992-01-14,34,Peak Earners,M,USA,Utah,Home,2,No,Website,Corporate Buyers
9998,Apartment,20,1062.33,Standard,2025-12-01,4,December,Monday,328980.19,Mid-market,Available,NaN,NaN,NaT,<NA>,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN
9999,Apartment,4,733.19,Compact,2025-12-01,4,December,Monday,217357.63,Budget,Available,NaN,NaN,NaT,<NA>,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN

---

### Saving The Dataset as `PowerBI Dataset`

In [34]:
# df.to_excel('PowerBI Dataset.xlsx', index=False)

---

### Saving The Model And Preprocesser

In [35]:
import joblib

In [36]:
# Saving The Preprocessor
joblib.dump(transform, 'preprocessor.pkl')

# Saving The Model
joblib.dump(model, 'model.pkl')

['model.pkl']